package numberbaseball;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class InputNumber {

    public static void inputNum() throws IOException {
        System.out.println("Type in 3 digits number :");
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        int randomNum = RandomNumberGenerator.numberGenerator();

        System.out.println("This is random number generated by computer :" + randomNum);

    }


}
